language: java
install:
- "./gradlew -b gradle/bootstrap.gradle bootstrap"
script:
- git describe --tags > VERSION.txt
- rm -rf .gradle gradle/.gradle .git
- zip -r sap-dtr-git-bridge.zip .
deploy:
  provider: releases
  api_key:
    secure: To0lP+dI0owu1pQGM+uNGs8LOz1PSouFM0+OLxtoLqCBjEtR5Y5fg+1ymohDViBeDN4V5mdwWjmzhE7JdhC/H1vJeBjDar6TOdPG0KO7YcccorI4ntFBSD4m4/fK0I1z1qP5ASy7NEnOcXLTpEsXYHf1ABG8bUWjZMliEmVYNM2fDR5+VCOKiXk0ux2pqCNG9KJT/dGSdH4KxkOmF3YWQpbO0jfvorwsLKfztX8MmfMYMPYiw1slLtkJuVDxLfu9DFfMkAeYRFvATpYKC7aYgPRvReF3Pg+t+7qpW904YW5CkztsIKiDirvmnXqyCHKoSfzHIiqBF0jxTAkoweih7eBdrqK+8QFCLQ+GUwMH1bnVnE+mhThqYFHX36BTn33ABJRpPOPO/UCooGw2qGtaLzKjciSlT/vYmNbXMA4384qYh/8Voj0NNieOetlko9jUGPMH5tTLl6/wvZgluwwB8whWIwNa8raqrq5xS6N/Kxxknzb98WIe8ptTQNTpcNJZ9PY2CvGOAiC+HsEEzKsG+cyzP75rgUQK/yJyzrshfiSMICXoc3O2wdhDYEpmMQNZwco0d4U98SPqvrUf8kokbMzlyQ8Y4IKN7rFvWckbx0WroNpMurrcWYeqbbjiq8l88541gGo+Vyj4D35+t139LjagonKkZO+rpwjN24ZWN9U=
  skip_cleanup: true
  file: sap-dtr-git-bridge.zip
  on:
    repo: cqse/sap-dtr-git-bridge
    tags: true
