language: java
install:
- "./gradlew -b gradle/bootstrap.gradle bootstrap"
script:
- git describe --tags > VERSION.txt
- rm -rf .gradle gradle/.gradle .git
- zip -r sap-dtr-git-bridge.zip .
deploy:
  provider: releases
  api_key:
    secure: "rVEWfrpVH+CCE2+5b3hQ94FWit8qhFO3wRHrpIsY72dXrLXT+aWjhglWQNos1oaiHggmj8XEB8ugLGKaElJr9MqvYtKoPl6cKMSOPfhXjgajYe2yDSovul17PoKReRsBn1lGXrW5ba5dJAco6lg8HIpFybqOuFBZT7HXqqyOFDr7gBwpM77tE2K0/U9OVcfafkg2uZ7PEaI9/d5yqKNxLuLMHHN2CYqlR1K/Gl0qD7R8rqUMD5k14fDh8kFjr4mVZWPlPVc9IrkGBRcxzytPpAUZIcewZUy6/L3+JA/old9SeAEvAajaoCpsAVurUxF9bToXclyg3ryO1q52S+45ghXBeE+bop7CRgSn16iXcp/h208CAJV2KODR58T07nP6NxuVvOzhnEc9PPNKILT0+gVvXD/dIdknl2ZWu9TQ7jGkMmybCDvkkerziQOBipT61BlCtydwSwCNuShUx+26AsE4AelTwha+MbNexP8lbLvW06V8YJUQSCz9PkX/yAeEPAcrwCRLW8qn7zEXplvbtfuHAJw67Q//EJagJtlOZy/OC8hdrMb53mVllAhUwWMCA6WfdzLZ+twHbQf10cevfnmXghL7mezklpf3n39JB+nalc1PfVf8DuCUjNp3lKoaNLTQzhXHugKfXeKxd7n03CUo2arG/u81U9sBIQsJUY8="
  skip_cleanup: true
  file: sap-dtr-git-bridge.zip
  on:
    repo: cqse/sap-dtr-git-bridge
    tags: true
